export const foundOn = [
    'Tiktok',
    'Event or conference',
    'Google',
    'Reddit',
    'Sales email',
    'Youtube',
    'Review site',
    'Podcast',
    'Referral or friend',
    'Previous user',
    'Newsletter',
    'LinkedIn',
    'Twitter',
    'Press',
    'Facebook or Instragram',
    'Used as client or another business',
    'Product Hunt',
    'Other',
  ];
  export const industries = [
    'Accounting and bookkeeping',
    'Construction',
    'Consulting',
    'Design',
    'Ecommerce',
    'Education',
    'Engineering',
    'Entertainment',
    'Finance',
    'Healthcare',
    'Insurance',
    'Legal',
    'Logisctics and transportation',
    'Manufacturing',
    'Marketing',
    'Nonprofit',
    'Real estate',
    'Recruiting and staffing',
    'Technology',
    'Travel and tourism',
    'Other',
  ];
  export const sizes = ['Just me', '2-5', '6-10', '11-50', '51-100', '100+'];
  export const clients = [
    "I don't have any clients yet",
    '1-10',
    '11-50',
    '51-100',
    '101-250',
    '251-1,000',
    '1,001-10,000',
    '10,001+',
  ];
  
export const types = ['Companies', 'Individuals', 'A mix of both'];